version: '2'
services:
  mysql8:
    image: mysql:8.0.13
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    command: mysqld --character-set-server=utf8
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: bridge
